---
title: "TPA Clean Code"
---

```{r}
setwd("/Users/*/Desktop")
```

```{r}
#set the working directory and load library
library(readxl)
library(reshape2)
library(dplyr)
```
```{r}
################################################################################################
##############################      Covert sheet sum to sheet tpa_data_long       ######################
################################################################################################

#reading Excel file
order1 = read_xlsx("/Users/*/Desktop/sum_copy.xlsx",
                   sheet = "sum",
                   col_names = TRUE, # use the first row as the name of the table
                   na = c("", "null"), # null values
                   n_max = 25) # the number of rows of order 1 data (not include column name row)
```

```{r}
head(order1)
```
```{r}
order2 = read_xlsx("/Users/*/Desktop/sum_copy.xlsx",
                   sheet = "sum",
                   col_names = TRUE,
                   na = c("", "null"),
                   skip = 26, # skip the number of rows in order 1 data
                   n_max = 25 ) # the number of rows of order 2 data (not include column name row)
```

```{r}
head(order2)
```
```{r}
#check discrepancies in column names...nothing major, just spacing characters
colnames(order1)[9:56] == colnames(order2)[57:104]
colnames(order2)[9:56] == colnames(order1)[57:104]
```
```{r}
#reorder columns of order2 to line up with column order from order1
order2.fixed = order2[,c(1:8, 57:104, 9:56)]
colnames(order2.fixed) = colnames(order1)
```

```{r}
head(order2.fixed)
```
```{r}
#vertically merge these together to create one big analysis dataset
analysis_dataset = rbind(order1, order2.fixed)
```
```{r}
head(analysis_dataset)
```
```{r}
#########################################################################################
###########       Going from analysis_dataset to analysis_dataset_long        ###########
#########################################################################################

# set up column names for long data, and reformatting
# add new column names after the 21 column of analysis_dataset
colnames.long = c(colnames(analysis_dataset)[1:21], "Experiment", "Type", "Number") 

# gsub function is used to replace the text within a dataframe
# read_xlsx assigned some column names new numbers (see line 15-26 running result ) so we need to fix it
colnames.long = gsub("Exp1_Recall1 ", "", colnames.long, fixed = TRUE) # there is a space after Exp1_Recall1?
colnames.long = gsub("...20", "", colnames.long, fixed = TRUE)
colnames.long = gsub("...21", "", colnames.long, fixed = TRUE)
colnames.long = gsub ("...55", "", colnames.long, fixed = TRUE)
colnames.long = gsub ("...56", "", colnames.long, fixed = TRUE)
colnames.long = gsub ("...68", "", colnames.long, fixed = TRUE)
colnames.long = gsub("\r\n", " ", colnames.long, fixed = TRUE) # I named the column with cmd+return to make it visually clean but when it comes to data reading I need to fix them using regular expression
```
```{r}
glimpse(analysis_dataset)
```

```{r}
# makw blank data frame for conversion to long format
# dim function here gets the dimension of the dataframe and it is multiplied by 8
analysis_dataset_long = as.data.frame(matrix(data = NA, nrow = 8*dim(analysis_dataset)[1], ncol = length(colnames.long))) # recall colnames.long contains all the column names we created on line71. 
colnames(analysis_dataset_long) = colnames.long # assign colnames.long to analysis_dataset_long's column names
```

```{r}
# getting list of ids
# unique() returns us a dataframe that duplicated data is being removed, here if there is a repeat in subject_name then that vector will be removed. Although the data does not have repeated subject_name doing this will double proof the data.
ids = unique(analysis_dataset$subject_name)
```

```{r}
#filling long data
# a for loop is written to repeatedly fill out the blank dataframe we created on line88
# i indicates id number; length of id equals to 50

for (i in 1:length(ids)){
  #within the analysis_dataset_long dataframe demographic information appears from column 1 to column 8
  analysis_dataset_long[c((8*(i - 1) + 1):(8*i)), 1:8] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 1:8]
  
  #Exp1_Recall1
  analysis_dataset_long[c(8*(i - 1) + 1), 9:21] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 9:21]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 1)] = 1
  analysis_dataset_long$Type[c(8*(i - 1) + 1)] = "Recall"
  analysis_dataset_long$Number[c(8*(i - 1) + 1)] = 1
  
  #Exp1_Picture1
  analysis_dataset_long[c(8*(i - 1) + 2), 9:19] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 22:32]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 2)] = 1
  analysis_dataset_long$Type[c(8*(i - 1) + 2)] = "Picture"
  analysis_dataset_long$Number[c(8*(i - 1) + 2)] = 1
  
  #Exp1_Picture2
  analysis_dataset_long[c(8*(i - 1) + 3), 9:19] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 33:43]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 3)] = 1
  analysis_dataset_long$Type[c(8*(i - 1) + 3)] = "Picture"
  analysis_dataset_long$Number[c(8*(i - 1) + 3)] = 2
  
  #Exp1_Recall2
  analysis_dataset_long[c(8*(i - 1) + 4), 9:21] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 44:56]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 4)] = 1
  analysis_dataset_long$Type[c(8*(i - 1) + 4)] = "Recall"
  analysis_dataset_long$Number[c(8*(i - 1) + 4)] = 2
  
  #Exp2_Recall1
  analysis_dataset_long[c(8*(i - 1) + 5), 9:21] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 57:69]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 5)] = 2
  analysis_dataset_long$Type[c(8*(i - 1) + 5)] = "Recall"
  analysis_dataset_long$Number[c(8*(i - 1) + 5)] = 3
  
  #Exp2_Phonology1
  analysis_dataset_long[c(8*(i - 1) + 6), 9:19] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 70:80]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 6)] = 2
  analysis_dataset_long$Type[c(8*(i - 1) + 6)] = "Phonology"
  analysis_dataset_long$Number[c(8*(i - 1) + 6)] = 3
  
  #Exp2_Phonology2
  analysis_dataset_long[c(8*(i - 1) + 7), 9:19] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 81:91]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 7)] = 2
  analysis_dataset_long$Type[c(8*(i - 1) + 7)] = "Phonology"
  analysis_dataset_long$Number[c(8*(i - 1) + 7)] = 4
  
  #Exp2_Recall2
  analysis_dataset_long[c(8*(i - 1) + 8), 9:21] = analysis_dataset[which(analysis_dataset$subject_name == ids[i]), 92:104]
  analysis_dataset_long$Experiment[c(8*(i - 1) + 8)] = 2
  analysis_dataset_long$Type[c(8*(i - 1) + 8)] = "Recall"
  analysis_dataset_long$Number[c(8*(i - 1) + 8)] = 4
  
}
```

```{r}
write.table(analysis_dataset_long,
            "/Users/*/Desktop/tpa_data_long_cleaned_xw.csv",
            sep = ",",
            row.names = FALSE,
            quote = FALSE)
```

```{r}
table = read.csv("/Users/*/Desktop/tpa_data_long_cleaned_xw.csv")
glimpse(table)
```


